name: Check User Permission

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          username: env.GITHUB_TRIGGERING_ACTOR
          require: 'write'
  
