name: Check User Permission

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        with:
          require: 'write'
          username: github.triggering_actor
  
