name: Check User Permission

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: ZheSun88/check-user-permission@main
        id: checkUser
        with:
          require: 'write'

      - name: close
        if: steps.checkUser.outputs.check-result == 'false'
        uses: actions-cool/issues-helper@v2.1.2
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}
