name: Check User Permission

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: ZheSun88/check-user-permission@main
        id: checkUser
        with:
          require: 'write'
  
